### ISSUE TITLE
Newsletter is in English

### ISSUE THREAD

**Issue by nowag** [jens1o/de-opensource.guide#1]
The German version of the **site** is of course in **German**. However, if you sign up to the **newsletter** it will be in **English**.
So in my opinion a little notice that users will sign up to an English newsletter on a German site would be great.

The POST method of signing up is found in `de-opensource.guide/_includes/footer.html` and uses the link `//github.us11.list-manage.com/subscribe/post?u=9d7ced8c4bbd6c2f238673f0f&amp;id=b514344ba3`

**Comment by jens1o** [comment]
Oh hi,

didn't expected that there is already something going on this repository. But that's a good idea, I'm going to do this now. :)

**Comment by jens1o** [comment]
oops

**Comment by jens1o** [comment]
I hope you're fine with the changes. In general, I would rather not touch the pure source files, because then I have a problem with syncing changes and this would complicate. If you have something I can improve, don't hesitate to ask.
