### ISSUE TITLE
_articles/de-DE/finding-users.md - Help people find and follow your project

### ISSUE THREAD

**Issue by timo2k** [jens1o/de-opensource.guide#18]
Translate the "Help people find and follow your project" Chapter.

https://github.com/jens1o/de-opensource.guide/blob/gh-pages/_articles/de-DE/finding-users.md

**Comment by timo2k** [comment]
Still working on it :]

**Comment by jens1o** [comment]
No worries.

I just noticed I worked on that already, just forgot to push it :D But perhaps it's a challenge for you and you can get used to it?

**Comment by jens1o** [comment]
https://github.com/jens1o/de-opensource.guide/commit/4c37efab8d31622377f8665613d202257b7ac07c

For reference :D

Maybe we can use the best of both?

**Comment by timo2k** [comment]
I think it is a waste of time when we work both on it in different branches with the same goal. Your version looks great for the moment. Iam going to another file. I think its more efficient :)

**Comment by jens1o** [comment]
resolved
